version: "3.7"

services:
  vobe_web:
    container_name: vobe-web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - '.:/app'
    - '/app/node_modules'
    ports:
    - '8080:8080'
