version: "3.7"

services:
  vobe_web:
    container_name: vobe-web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .\Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    ports:
    - '80:80'

volumes:
  caddy-data:
  caddy-config:

