version: "3.7"

services:
  vobe_web:
    container_name: vobe-web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./maintenance/:/usr/share/caddy/maintenance
      - caddy-data:/data
      - caddy-config:/config
    ports:
    - '80:80'
    - '443:443'
    networks:
      - vobe

volumes:
  caddy-data:
  caddy-config:

networks:
  vobe:
    external: true
